baseURL = "https://george.czabania.com/"
languageCode = "en-nz"
title = "George Czabania"
publishDir = "docs"
theme = "slim"

[params]
  # Subtitle = ""
  GithubID = "stayradiated"
  TwitterID = "stayradiated"
  AnalyticsID = "UA-106147104-1"
  # DisqusShortname = "Your Disqus shortname"
  Summary = true  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
  FooterMsg = "&copy; George Czabania 2017"
